---
- hosts: spacewalk
  remote_user: root

  tasks:
  - name: Add Spacewalk repo
    command: yum localinstall -y https://copr-be.cloud.fedoraproject.org/results/%40spacewalkproject/spacewalk-2.9/epel-7-x86_64/00912457-spacewalk-repo/spacewalk-repo-2.9-4.el7.noarch.rpm
  - name: Add EPEL repo
    command: yum localinstall -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  - name: Install Spacewalk
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - spacewalk-setup-postgresql
      - spacewalk-postgresql
  - firewalld:
      service: http
      permanent: yes
      state: enabled
  - firewalld:
      service: https
      permanent: yes
      state: enabled
  - firewalld:
      port: 5222/tcp
      permanent: yes
      state: enabled
  - firewalld:
      port: 5269/tcp
      permanent: yes
      state: enabled
  - firewalld:
      port: 69/udp
      permanent: yes
      state: enabled
